name: AOC2018
version: 0.1.0.0
github: 'irvinlim/advent-of-code-2018'
license: MIT
author: 'Irvin Lim'
maintainer: 'irvinlimweiquan@gmail.com'
copyright: '2018 Irvin Lim'

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/irvinlim/advent-of-code-2018#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text

library:
  source-dirs: src

executables:
  SubmitAnswer:
    main: SubmitAnswer.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AOC2018
      - bytestring
      - http-client
      - http-client-tls
      - uri-encode

tests:
  AOC2018-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AOC2018
      - HUnit
